### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by ladrua** [DivanteLtd/vue-storefront#1775]
I am trying to bring up the project with `docker-compose up` but getting this error:

```
vue_1       | yarn install v1.9.4
vue_1       | [1/5] Validating package.json...
vue_1       | [2/5] Resolving packages...
vue_1       | [3/5] Fetching packages...
vue_1       | info fsevents@1.2.4: The platform "linux" is incompatible with this module.
vue_1       | info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
vue_1       | [4/5] Linking dependencies...
vue_1       | warning " > karma-webpack@3.0.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
vue_1       | [5/5] Building fresh packages...
vue_1       | success Saved lockfile.
vue_1       | Done in 9.89s.
vue_1       | yarn run v1.9.4
vue_1       | $ cross-env NODE_ENV=production webpack --config ./core/build/webpack.prod.client.config.js --mode production --progress --hide-modules
vue_1       | WARNING: NODE_ENV value of 'docker' did not match any deployment config file names.
vue_1       | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/de-DE.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/en-US.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/es-ES.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/fr-FR.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/it-IT.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/jp-JP.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/nl-NL.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/pl-PL.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/pt-BR.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/ru-RU.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/theme-default/resource/i18n/en-US.csv
vue_1       | Writing JSON file: de-DE.json
vue_1       | Writing JSON file: en-US.json
vue_1       | Writing JSON file: es-ES.json
vue_1       | Writing JSON file: fr-FR.json
vue_1       | Writing JSON file: it-IT.json
vue_1       | Writing JSON file: jp-JP.json
vue_1       | Writing JSON file: nl-NL.json
vue_1       | Writing JSON file: pl-PL.json
vue_1       | Writing JSON file: pt-BR.json
vue_1       | Writing JSON file: ru-RU.json
vue_1       | Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
vue_1       |  - configuration.module.rules[3].include should be one of these:
vue_1       |    RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? } | [RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? }]
vue_1       |    -> One or multiple rule conditions
vue_1       |    Details:
vue_1       |     * configuration.module.rules[3].include should be an instance of RegExp
vue_1       |     * configuration.module.rules[3].include should be a string.
vue_1       |     * configuration.module.rules[3].include should be an instance of function
vue_1       |     * configuration.module.rules[3].include[0] should be an instance of RegExp
vue_1       |     * configuration.module.rules[3].include[0]: The provided value "@vue-storefront" is not an absolute path!
vue_1       |     * configuration.module.rules[3].include[0] should be an instance of function
vue_1       |     * configuration.module.rules[3].include[0] should be an array:
vue_1       |       [RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? }]
vue_1       |     * configuration.module.rules[3].include[0] should be an object.
vue_1       |     * configuration.module.rules[3].include should be an object.
vue_1       |     * configuration.module.rules[3].include[0] should be an instance of RegExp
vue_1       |     * configuration.module.rules[3].include[0]: The provided value "@vue-storefront" is not an absolute path!
vue_1       |     * configuration.module.rules[3].include[0] should be an instance of function
vue_1       |     * configuration.module.rules[3].include[0] should be an array:
vue_1       |       [RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? }]
vue_1       |     * configuration.module.rules[3].include[0] should be an object.
vue_1       | error Command failed with exit code 1.
vue_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
vue_1 exited with code 1
```

The only thing that I have changed is in the docker-compose.yml file, as I have other apps in the same project the vue-storefront is in a subdir, so I have updated the Volume mounts to reflect the new path:

```
vue:
      # image: divante/vue-storefront:latest
      build:
        context: ./vue-storefront
        dockerfile: docker/vue-storefront/Dockerfile
      env_file: ./vue-storefront/docker/vue-storefront/default.env
      environment:
        VS_ENV: dev
      volumes:
        - './vue-storefront/babelrc:/var/www/.babelrc'
        - './vue-storefront/config:/var/www/config'
        - './vue-storefront/core:/var/www/core'
        - './vue-storefront/ecosystem.json:/var/www/ecosystem.json'
        - './vue-storefront/.eslintignore:/var/www/.eslintignore'
        - './vue-storefront/.eslintrc.js:/var/www/.eslintrc.js'
        - './vue-storefront/lerna.json:/var/www/lerna.json'
        - './vue-storefront/package.json:/var/www/package.json'
        - './vue-storefront/src:/var/www/src'
        - './vue-storefront/var:/var/www/var'
        - './vue-storefront/tsconfig.json:/var/www/tsconfig.json'
        - './vue-storefront/shims.d.ts:/var/www/shims.d.ts'
      tmpfs:
        - /var/www/dist
      ports:
        - '3000:3000'
```
