### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by roboto-cloud** [DivanteLtd/vue-storefront#189]
someone know how fix it in **vue-storefront-api**?

**npm run dev**
```
> vue-storefront-api@0.1.0 dev /mnt/_/dev/base/production.dpl/storefront/vue-storefront-api
> nodemon -w src --exec "babel-node src --presets es2015,stage-0"
[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /mnt/_/dev/base/production.dpl/storefront/vue-storefront-api/src/**/*
[nodemon] starting `babel-node src --presets es2015,stage-0`
[nodemon] Internal watch failed: watch /mnt/_/dev/base/production.dpl/storefront/vue-storefront-api/src ENOSPC
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront-api@0.1.0 dev: `nodemon -w src --exec "babel-node src --presets es2015,stage-0"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-storefront-api@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jujes/.npm/_logs/2017-10-27T15_31_02_126Z-debug.log
```

**Comment by patrykpiston** [comment]
What system are you running it on? Also this may help

https://github.com/remy/nodemon/issues/239

**Comment by roboto-cloud** [comment]
@patrykpiston 

Linux stackup 4.13.8-1-ARCH #1 SMP PREEMPT Wed Oct 18 11:49:44 CEST 2017 x86_64 GNU/Linux
node -> v8.5.0
npm -> 5.3.0

**Comment by pkarw** [comment]
Could you attach the content of log file mentioned above?

**Comment by roboto-cloud** [comment]
yes, here 2017-10-27T15_18_30_622Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/jujes/.nvm/versions/node/v8.5.0/bin/node',
1 verbose cli   '/home/jujes/.nvm/versions/node/v8.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.3.0
3 info using node@v8.5.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-storefront-api@0.1.0~predev: vue-storefront-api@0.1.0
6 info lifecycle vue-storefront-api@0.1.0~dev: vue-storefront-api@0.1.0
7 verbose lifecycle vue-storefront-api@0.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-storefront-api@0.1.0~dev: PATH: /home/jujes/.nvm/versions/node/v8.5.0/lib/node_modules/npm/bin/node-gyp-bin:/mnt/_/dev/base/pr$
duction.dpl/storefront/vue-storefront-api/node_modules/.bin:/home/jujes/.nvm/versions/node/v8.5.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin$
site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle vue-storefront-api@0.1.0~dev: CWD: /mnt/_/dev/base/production.dpl/storefront/vue-storefront-api
10 silly lifecycle vue-storefront-api@0.1.0~dev: Args: [ '-c',
10 silly lifecycle   'nodemon -w src --exec "babel-node src --presets es2015,stage-0"' ]
11 silly lifecycle vue-storefront-api@0.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle vue-storefront-api@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: vue-storefront-api@0.1.0 dev: `nodemon -w src --exec "babel-node src --presets es2015,stage-0"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/jujes/.nvm/versions/node/v8.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/jujes/.nvm/versions/node/v8.5.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid vue-storefront-api@0.1.0
15 verbose cwd /mnt/_/dev/base/production.dpl/storefront/vue-storefront-api
16 verbose Linux 4.13.8-1-ARCH
17 verbose argv "/home/jujes/.nvm/versions/node/v8.5.0/bin/node" "/home/jujes/.nvm/versions/node/v8.5.0/bin/npm" "run" "dev"
18 verbose node v8.5.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-storefront-api@0.1.0 dev: `nodemon -w src --exec "babel-node src --presets es2015,stage-0"`
22 error Exit status 1
23 error Failed at the vue-storefront-api@0.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by roboto-cloud** [comment]
@pkarw @patrykpiston I think this issue come from npm... 
if I use yarn all work properly..

one more think about **Performance** and **PWA** the attached capture come from chrome audit, in the case for for production this values average are the same?
![screenshot from 2017-10-27 20-08-13](https://user-images.githubusercontent.com/32390825/32118717-fffa7f8e-bb52-11e7-886d-12e6068dacbc.png)

thanks in advance,

**Comment by pkarw** [comment]
Thanks! On production we do have quite better results but still many things need to be optimized:
- offscreen images
- service worker tunning
- image sizes - particularly on home page

Category and product pages are much faster (yesterday I got something around 75 of performance on category - still should be better)

Also - we have issue for preparing PWA manifest so this also is to be done


Right now we’re focusing on checkout functionality to open public demo. Then we’ll work continuously on performance

**Comment by roboto-cloud** [comment]
thanks @pkarw!!!
Please think about [essential and easy deploy](https://github.com/cezerin/cezerin) using [all in one docker-compose.yml ](https://github.com/DivanteLtd/vue-storefront/issues/151)I work with traefik as proxy and put here some ideas:

```
version: "3"

networks:
  comp_proxy:
    external: true
  internal:
    external: false

services:
  demo.vuestorefront.io:
    container_name: demo.vuestorefront.io
    restart: always
    image: vuestorefront/vue-storefront:latest
    environment:
      ROOT_URL: "https://demo.vuestorefront.io"
      STORE_EMAIL: "demo@vuestorefront.io"
      STORE_USER: "demo"
      STORE_AUTH: "aasd(/)Asa8d811"
    labels:
      - "traefik.backend=vuestorefront.io"
      - "traefik.frontend.rule=Host:vuestorefront.io"
      - "traefik.docker.network=comp_proxy"
      - "traefik.port=3000"
    networks:
      - internal
      - comp_proxy
    links:
      - es.vuestorefront.io:es1
    depends_on:
      - es.vuestorefront.io
```
