### ISSUE TITLE
Add ./packages as volume to docker-compose.yml

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#3251]
## Current behavior
If you start VSF via `docker-compose` the following error occurs:
```
yarn install v1.13.0
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find any versions for "@vue-storefront/module" that matches "^0.0.9"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

It's neccessary to add the `./packages` folder to the `docker-compose.yml` like:
```yaml
services:
  app:
    # image: divante/vue-storefront:latest
    build:
      context: .
      dockerfile: docker/vue-storefront/Dockerfile
    env_file: docker/vue-storefront/default.env
    environment:
      VS_ENV: dev
    network_mode: host
    volumes:
      - './babel.config.js:/var/www/babel.config.js'
      - './config:/var/www/config'
      - './core:/var/www/core'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './.eslintignore:/var/www/.eslintignore'
      - './.eslintrc.js:/var/www/.eslintrc.js'
      - './lerna.json:/var/www/lerna.json'
      - './tsconfig.json:/var/www/tsconfig.json'
      - './tsconfig-build.json:/var/www/tsconfig-build.json'
      - './shims.d.ts:/var/www/shims.d.ts'
      - './package.json:/var/www/package.json'
      - './src:/var/www/src'
      - './var:/var/www/var'
      - './packages:/var/www/packages'
    tmpfs:
      - /var/www/dist
    ports:
      - '3000:3000'
```

## Expected behavior

It should build and run the app on start.

## Steps to reproduce the issue

Just run `docker-compose up`

## Repository

develop

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: none 
- OS: all 
- Node: default 
- Code Version: develop
